language: julia

os:
  - linux

julia:
  - 0.5
  - 0.6

notifications:
  email: false

sudo: true

before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) restricted"
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq -y
  - sudo apt-get install g++-4.7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 100
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.6 50
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 100
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 50
  - sudo update-alternatives --install /usr/bin/cpp cpp-bin /usr/bin/cpp-4.7 100
  - sudo update-alternatives --install /usr/bin/cpp cpp-bin /usr/bin/cpp-4.6 50
  - sudo update-alternatives --set g++ /usr/bin/g++-4.7
  - sudo update-alternatives --set gcc /usr/bin/gcc-4.7
  - sudo update-alternatives --set cpp-bin /usr/bin/cpp-4.7
  - sudo apt-get install -qq fglrx opencl-headers libboost-program-options-dev libfftw3-dev libgtest-dev
  - sudo apt-get install libpcre3-dev -y

install:
  - mkdir -p bin/gTest
  - cd bin/gTest
  - cmake -DCMAKE_BUILD_TYPE=Release /usr/src/gtest
  - make
  - sudo mv libg* /usr/lib

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p deps/
  - cd deps/
  - git clone https://github.com/clMathLibraries/clFFT
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p bin/clFFT
  - cd bin/clFFT
  - cmake -DBoost_NO_SYSTEM_PATHS=OFF -DBUILD_TEST=OFF -DCMAKE_CXX_FLAGS="-std=c++11" ${TRAVIS_BUILD_DIR}/deps/clFFT/src
  - sudo make install
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/bin/clFFT/library:${LD_LIBRARY_PATH}
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/bin/clFFT/statTimer:${LD_LIBRARY_PATH}
  - cd ${TRAVIS_BUILD_DIR}
